# framework:
#     messenger:
#         failure_transport: failed

#         transports:
#             async: '%env(MESSENGER_TRANSPORT_DSN)%'
#             sync: 'sync://'
#             failed: 'doctrine://default?queue_name=failed'
#             scheduler_default: 'sync://'

#         default_bus: messenger.bus.default

#         buses:
#             messenger.bus.default:
#                 middleware:
#                     - doctrine_transaction
#                     - doctrine_ping_connection

#         routing:
#             Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#             Symfony\Component\Notifier\Message\ChatMessage: async
#             Symfony\Component\Notifier\Message\SmsMessage: async
#             App\Domain\CurrencyExchange\UpdateExchangeRatesMessage: sync

# when@test:
#     framework:
#         messenger:
#             reset_on_message: true

# when@dev:
#     framework:
#         messenger:
#             failure_transport: failed

# when@prod:
#     framework:
#         messenger:
#             failure_transport: failed

# services:
#     _defaults:
#         autowire: true
#         autoconfigure: true

#     App\Domain\CurrencyExchange\UpdateExchangeRatesHandler:
#         arguments:
#             $application: 'Symfony\Component\Console\Application'

#     App\Domain\CurrencyExchange\UpdateExchangeRatesCommand:
#         arguments:
#             $currencyRateTTL: '%env(CURRENCY_RATES_TTL)%'
#             $baseCurrency: '%env(BASE_CURRENCY)%'