
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mintos-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app:delegated        # `:delegated` improves Linux/macOS mount perf
    networks:
      - mintos-network

  nginx:
    image: nginx:alpine
    container_name: mintos-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated
      - /app/vendor
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - mintos-network

networks:
  mintos-network:
    driver: bridge
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
