<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250610192056 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE "accounts" (id UUID NOT NULL, name VARCHAR(100) NOT NULL, balance BIGINT NOT NULL, currency VARCHAR(3) NOT NULL, user_id UUID NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_CAC89EACA76ED395 ON "accounts" (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "transaction_entries" (id UUID NOT NULL, type VARCHAR(6) NOT NULL, amount BIGINT NOT NULL, currency VARCHAR(3) NOT NULL, transaction_id UUID NOT NULL, account_id UUID NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5B528F272FC0CB0F ON "transaction_entries" (transaction_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5B528F279B6B5FBA ON "transaction_entries" (account_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "transactions" (id UUID NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "users" (id UUID NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "accounts" ADD CONSTRAINT FK_CAC89EACA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "transaction_entries" ADD CONSTRAINT FK_5B528F272FC0CB0F FOREIGN KEY (transaction_id) REFERENCES "transactions" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "transaction_entries" ADD CONSTRAINT FK_5B528F279B6B5FBA FOREIGN KEY (account_id) REFERENCES "accounts" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE "accounts" DROP CONSTRAINT FK_CAC89EACA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "transaction_entries" DROP CONSTRAINT FK_5B528F272FC0CB0F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE "transaction_entries" DROP CONSTRAINT FK_5B528F279B6B5FBA
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "accounts"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "transaction_entries"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "transactions"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "users"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE messenger_messages
        SQL);
    }
}
